remote_theme: pages-themes/minimal@v0.2.0
plugins:
- jekyll-remote-theme # add this line to the plugins list if you already have one
title: "Hexx's Study Notes"
description: "This repository displays my personal study notes across various tech subjects, showcasing my continuous learning and expertise in all things related to computer science."